apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wagtail-example-image-resource
  namespace: wagtail-pipeline
spec:
  type: image
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/wagtail-pipeline/wagtail-img:latest'
    - name: digest
      value: 
