apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wagtail
  name: wagtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wagtail
  template:
    metadata:
      labels:
        app: wagtail
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/my-pipeline/wagtail:latest
          imagePullPolicy: Always
          name: wagtail
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
