
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wagtail-example
  name: wagtail-example
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: wagtail-example
    weight: 100
